### ISSUE TITLE
Reported conflict with Yoast SEO

### ISSUE THREAD

**Issue by tacoverdo** [easypropertylistings/Easy-Property-Listings#156]
**Problem description**
When Yoast SEO (Premium) is active and social information for Facebook or Twitter is switched on, HTML code is added to the head of property page when Easy Property Listings is set to compatibility mode.

**Possible cause**
In its social functions, Yoast SEO calls the filter `the_content` to check the content. When the compatibility mode is activated, EPL returns HTML when `the_content` is called.
Doing action on `the_content`: [template-functions.php line 1576](https://github.com/easypropertylistings/Easy-Property-Listings/blob/master/lib/includes/template-functions.php#L1576)
If you follow what's happening there, you'll find that this function is called; [template-functions.php line 134](https://github.com/easypropertylistings/Easy-Property-Listings/blob/master/lib/includes/template-functions.php#L134)
Finally that hard includes a file; [template-functions.php line 177](https://github.com/easypropertylistings/Easy-Property-Listings/blob/master/lib/includes/template-functions.php#L177)

**Possible solution**
Check if `the_content` is called in the loop, or do not include/require HTML when a filter is used.

**Tested versions**
WordPress 4.4
Yoast SEO 3.0.7
EPL 2.3.1

**Comment by mervb** [comment]
The Theme Compatibility mode is just that. An attempt to solve users issues is performing theme setup.

Wish wordpress had a filter for the get_template_part but alas, still no fix there.

The particular user who raised this issue was directed to the template file for the Avada theme here 
http://codex.easypropertylistings.com.au/article/185-theme-templates
which allows them to disable the theme compatibility mode and use WordPress the correct way.


-------------------
Theme Setup - Are you feeling lucky?
-------------------
The latest release of Easy Property Listings includes a theme compatibility mode that works great for most themes. Once you have activated the plugin visit Dashboard > Easy Property Listings > Settings > Theme Setup. Before you enable the theme compatibility mode, add a listing and preview. If it looks great, you are good to go, however if your listing is too wide or your sidebar is in the wrong place activate Theme Compatibility mode. Next adjust the Theme Setup: Featured Images to adjust how your featured images appear. If you see two featured images play with the settings until it looks great.

**Comment by mervb** [comment]
That filter is only active with theme compatibility mode. The best solution is for the user to perform Theme Setup which we provide many ready to add templates. Then there is the whole "use a child theme "issue...

**Comment by mervb** [comment]
Theme Setup is the best practice
http://codex.easypropertylistings.com.au/article/49-theme-setup

We have many ready to use templates for popular WordPress themes
http://codex.easypropertylistings.com.au/article/185-theme-templates
